name: keycloak_element

services:
  element-web:
    image: vectorim/element-web
    ports:
      - "8081:80"
    volumes:
      - ./config.json:/app/config.json

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.2
    container_name: keycloak
    ports:
      - "8085:8080"
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
